version: '3.8'

services:
  rtmp-server:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./backend:/app/backend
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - DEBUG=False
      - DB_URL=sqlite:////app/data/streams.db
      - LOG_LEVEL=INFO
      - REMOTE_RTMP_URL=rtmp://ali.push.yximgs.com/live/
      - LOCAL_RTMP_URL=rtmp://srs:1935/live/
      - PYTHONUNBUFFERED=1
    depends_on:
      - srs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  srs:
    image: ossrs/srs:4
    ports:
      - "1935:1935"  # RTMP
      - "1985:1985"  # HTTP API
      - "8080:8080"  # HTTP-FLV
    volumes:
      - ./conf/srs.conf:/usr/local/srs/conf/srs.conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1985/api/v1/versions"]
      interval: 30s
      timeout: 10s
      retries: 3