version: '3'

services:
  rtmp-server:
    image: zhoujie218/rtmp-server:latest
    container_name: rtmp-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
      - ./streams:/app/streams
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai
      - APP_VERSION=${VERSION:-latest}
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000