version: '3.8'

services:
  rtmp-server:
    build: 
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - "10088:10088"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./backend:/app/backend
    environment:
      - PORT=10088
      - HOST=0.0.0.0
      - DEBUG=True
      - DB_URL=sqlite:///data/streams.db
      - LOG_LEVEL=DEBUG
      - REMOTE_RTMP_URL=rtmp://ali.push.yximgs.com/live/
      - LOCAL_RTMP_URL=rtmp://srs:1935/live/
      - PYTHONUNBUFFERED=1
      - FLASK_APP=backend/app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    depends_on:
      - srs
    restart: unless-stopped
    working_dir: /app
    command: flask run --host=0.0.0.0 --port=10088
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  srs:
    image: ossrs/srs:4
    platform: ${TARGETPLATFORM:-linux/amd64}
    ports:
      - "1935:1935"
      - "1985:1985"
      - "8080:8080"
    volumes:
      - ./conf/srs.conf:/usr/local/srs/conf/srs.conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1985/api/v1/versions"]
      interval: 30s
      timeout: 10s
      retries: 3