version: '3.8'

services:
  stream-server:
    image: zhoujie218/rtmp-serve:latest
    container_name: rtmp-serve
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
      - ./streams:/app/streams
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai 