version: '3.8'

services:
  rtmp-server:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - DEBUG=False
      - DB_URL=sqlite:////app/data/streams.db
      - LOG_LEVEL=INFO
      - REMOTE_RTMP_URL=rtmp://ali.push.yximgs.com/live/
      - LOCAL_RTMP_URL=rtmp://srs:1935/live/
    depends_on:
      - srs
    restart: unless-stopped

  srs:
    image: ossrs/srs:4
    ports:
      - "1935:1935"  # RTMP
      - "1985:1985"  # HTTP API
      - "8080:8080"  # HTTP-FLV
    volumes:
      - ./conf/srs.conf:/usr/local/srs/conf/srs.conf
    restart: unless-stopped