version: '3'
services:
  srs:
    image: ossrs/srs:4
    ports:
      - "1935:1935"  # RTMP
      - "8080:8080"  # HTTP-FLV
      - "1985:1985"  # API
    volumes:
      - ./conf/srs.conf:/usr/local/srs/conf/srs.conf
    restart: always

  rtmp-server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "10088:10088"
    volumes:
      - ./:/app
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - PORT=10088
      - HOST=0.0.0.0
      - DEBUG=True
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    depends_on:
      - srs
    restart: always
    working_dir: /app
    command: ["gunicorn", "--log-level", "debug", "-w", "4", "-b", "0.0.0.0:10088", "backend.app:app"]